/**
 * NEXUS Cards API — List and Create
 *
 * GET  /api/nexus/cards?project_id=...&lane=ready&bender_lane=executing&assigned_to=...
 * POST /api/nexus/cards  { lane, title, card_type, project_id, ... }
 *
 * Schema V2: Board=Project, card_id auto-generated by DB trigger.
 * DEA-042 | Phase 1
 */

import { NextRequest, NextResponse } from 'next/server'
import { tables } from '@/lib/server/database'
import type { NexusCardCreate, CardLane, BenderLane } from '@/types/nexus'

export async function GET(request: NextRequest) {
  try {
    const params = request.nextUrl.searchParams
    const lane = params.get('lane')
    const bender_lane = params.get('bender_lane')
    const project_id = params.get('project_id')
    const assigned_to = params.get('assigned_to')
    const delegation_tag = params.get('delegation_tag')
    const card_type = params.get('card_type')
    const parent_id = params.get('parent_id')
    const due_before = params.get('due_before')
    const due_after = params.get('due_after')
    const limit = parseInt(params.get('limit') || '100', 10)

    let query = tables.nexus_cards
      .select('*')
      .order('created_at', { ascending: true })
      .limit(Math.min(limit, 500))

    if (lane) {
      const lanes = lane.split(',') as CardLane[]
      if (lanes.length === 1) {
        query = query.eq('lane', lanes[0])
      } else {
        query = query.in('lane', lanes)
      }
    }
    if (bender_lane) {
      const benderLanes = bender_lane.split(',') as BenderLane[]
      if (benderLanes.length === 1) {
        query = query.eq('bender_lane', benderLanes[0])
      } else {
        query = query.in('bender_lane', benderLanes)
      }
    }
    if (project_id) query = query.eq('project_id', project_id)
    if (assigned_to) query = query.eq('assigned_to', assigned_to)
    if (delegation_tag) query = query.eq('delegation_tag', delegation_tag)
    if (card_type) query = query.eq('card_type', card_type)
    if (parent_id) {
      if (parent_id === 'null') {
        query = query.is('parent_id', null)
      } else {
        query = query.eq('parent_id', parent_id)
      }
    }
    if (due_before) query = query.lte('due_date', due_before)
    if (due_after) query = query.gte('due_date', due_after)

    const { data, error } = await query
    if (error) {
      return NextResponse.json(
        { error: { code: 'FETCH_ERROR', message: error.message } },
        { status: 500 }
      )
    }

    return NextResponse.json({ data, cached: false })
  } catch (error) {
    console.error('GET /api/nexus/cards error:', error)
    return NextResponse.json(
      { error: { code: 'INTERNAL_ERROR', message: 'Failed to list cards' } },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const body: NexusCardCreate = await request.json()

    if (!body.lane || !body.title || !body.card_type) {
      return NextResponse.json(
        { error: { code: 'VALIDATION_ERROR', message: 'lane, title, and card_type are required' } },
        { status: 400 }
      )
    }

    const { data, error } = await tables.nexus_cards
      .insert(body)
      .select()
      .single()

    if (error) {
      return NextResponse.json(
        { error: { code: 'CREATE_ERROR', message: error.message } },
        { status: 500 }
      )
    }

    // Emit card.created event
    await tables.nexus_events.insert({
      event_type: 'card.created',
      card_id: data.id,
      actor: 'dea',
      payload: { card_id: data.card_id, lane: body.lane, title: body.title },
    })

    return NextResponse.json({ data, cached: false }, { status: 201 })
  } catch (error) {
    console.error('POST /api/nexus/cards error:', error)
    return NextResponse.json(
      { error: { code: 'INTERNAL_ERROR', message: 'Failed to create card' } },
      { status: 500 }
    )
  }
}
